// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_lCCEBuONr83j7BCKdkVzkEJIxhCds0',
    appId: '1:699104574106:web:630b17c7b507322a76fd23',
    messagingSenderId: '699104574106',
    projectId: 'zenchat-966ef',
    authDomain: 'zenchat-966ef.firebaseapp.com',
    storageBucket: 'zenchat-966ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDidHudUy0nylrmIDx5wlwzJvVoMt5r9Zk',
    appId: '1:699104574106:android:2a540569c9188a7176fd23',
    messagingSenderId: '699104574106',
    projectId: 'zenchat-966ef',
    storageBucket: 'zenchat-966ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJQV2KMkhgEf8u2vPPN2bkoCv2XCUKq4',
    appId: '1:699104574106:ios:481960ea1f93a9b876fd23',
    messagingSenderId: '699104574106',
    projectId: 'zenchat-966ef',
    storageBucket: 'zenchat-966ef.appspot.com',
    iosBundleId: 'com.example.zenchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrJQV2KMkhgEf8u2vPPN2bkoCv2XCUKq4',
    appId: '1:699104574106:ios:22fd8cda336c6c7776fd23',
    messagingSenderId: '699104574106',
    projectId: 'zenchat-966ef',
    storageBucket: 'zenchat-966ef.appspot.com',
    iosBundleId: 'com.example.zenchat.RunnerTests',
  );
}
